# Generated by Django 5.1.1 on 2025-04-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_shipping',
            field=models.BooleanField(default=False, verbose_name='ارسال رایگان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quality',
            field=models.CharField(choices=[('d1', 'درجه یک'), ('d2', 'درجه دو'), ('d3', 'درجه سه'), ('d4', 'درجه چهار')], max_length=20, verbose_name='(کیفی) کیفیت محصول'),
        ),
    ]
