# Generated by Django 5.1.1 on 2025-04-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_free_shipping_alter_product_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discription',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات بیشتر برای محصول'),
        ),
    ]
