# Generated by Django 5.1.1 on 2025-05-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_order',
            field=models.FloatField(blank=True, null=True, verbose_name='حداکثر سفارش (کیلوگرم - خالی برای بدون محدودیت)'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_order',
            field=models.FloatField(blank=True, null=True, verbose_name='حداقل سفارش (کیلوگرم - خالی برای بدون محدودیت)'),
        ),
    ]
