# Generated by Django 5.1.1 on 2025-05-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_max_order_product_min_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('akbari', 'اکبری'), ('fandoghi', 'فندوقی'), ('ahmadaghaii', 'احمد آقایی'), ('kaleghoochi', 'کله قوچی'), ('shahpasand', 'شاه پسند'), ('sefid', 'سفید'), ('badami', 'بادامی'), ('khanjari', 'خنجری'), ('makhloot', ' مخلوط')], max_length=20, verbose_name='نوع پسته'),
        ),
    ]
