# Generated by Django 5.1.1 on 2025-05-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=13, null=True, verbose_name='(تومان) هزینه ارسال'),
        ),
    ]
